### ISSUE TITLE
about MDSR (JPEG)*

### ISSUE THREAD

**Issue by suke27** [thstkdgus35/EDSR-PyTorch#1]
hi, I want to ask about MDSR (JPEG)*, is it have special operation for train model? I found the result from MDSR (JPEG)* have big difference with others.
Plz share it. Thank you!

**Comment by thstkdgus35** [comment]
Hello.

I mixed JPEG images in the training dataset, so that MDSR can also learn JPEG deblocking, too.

Maybe you can try this method by yourself without big problems.

Thank you.

**Comment by suke27** [comment]
do you train the MDSR (JPEG) using DIV2k too, where are mixed jpeg images from
and what is Epoch number are you use for MDSR baseline
Plz help to check , Thank you!

**Comment by suke27** [comment]
I train the model follow your guide, but when I do test using snapshot model_lastest.pt file(training not done), the result is bad, it look like a black layer over original image, is it mean i train in wrong way?

**Comment by thstkdgus35** [comment]
I converted DIV2K images to JPEG file and used them. Other settings are same with the original MDSR training. For the training, I will check and give you the answer.

Thank you.

**Comment by suke27** [comment]
hi, you said mixed jpeg images during training will get better result for jpeg images
but when training mixed jpeg (300 jpegs in 900 training dataset), result not good as yours. could you share more information for it

**Comment by suke27** [comment]
thank you for reply!
