### ISSUE TITLE
questions about weights Initialization and rgb_range

### ISSUE THREAD

**Issue by Zheng222** [thstkdgus35/EDSR-PyTorch#10]
Hello, I cannot find that this code employs specific initialization method. I remember the gaussian filler is used in the previous version. If you don't mind, please interpret this issue. In addition, the 'rgb_range' in the code is set to 255, and this setting makes the input data ranging from [0, 255], which is different from usual data range [0, 1].  I want to know this way whether makes the training faster and more stable. @thstkdgus35

**Comment by thstkdgus35** [comment]
Hello, Zheng.

We use default initialization method supported by PyTorch.

I remember that it was 'He initialization', which first proposed in https://arxiv.org/abs/1502.01852 (Delving into Deep Rextifiers by Kaiming He.)

Also, we found that rgb_range = [0, 255] makes our system to converge faster.

Thank you.

Sanghyun.
