### ISSUE TITLE
How to trian only on Y channel?

### ISSUE THREAD

**Issue by YongboLiang** [thstkdgus35/EDSR-PyTorch#101]
Hi, I want to try train the model only on Y channel. How should I do? Change n_colors from 3 to 1? Is there any other place that needs to be changed?
Best~~

**Comment by dongxijia** [comment]
Hi, I got the same problem, Had you handled it?

**Comment by zpkosmos** [comment]
@dongxijia 
I solve this problem by change：
1.set --n_colors =1
2.data common.py：line27：   
ret = [
        args[0][iy:iy + ip, ix:ix + ip],
        *[a[ty:ty + tp, tx:tx + tp] for a in args[1:]]
    ]

3.data common.py：lin65-67：
        if hflip: img = img[:, ::-1]
        if vflip: img = img[::-1, :]
        if rot90: img = img.transpose(1, 0)

**Comment by yanmenglu** [comment]
@zpkosmos, when I change the code like yours, but training meet errors.
![image](https://user-images.githubusercontent.com/23131833/59688214-d0fe4400-920f-11e9-8eb7-62b4502dd116.png) could you tell me how to fix this error?

**Comment by zpkosmos** [comment]
> @zpkosmos, when I change the code like yours, but training meet errors.
> ![image](https://user-images.githubusercontent.com/23131833/59688214-d0fe4400-920f-11e9-8eb7-62b4502dd116.png) could you tell me how to fix this error?

中国人的话加qq1808791262
mdsr我没试过
