### ISSUE TITLE
EDSR_baseline pretrained model file

### ISSUE THREAD

**Issue by Zheng222** [thstkdgus35/EDSR-PyTorch#102]
@thstkdgus35 Hello, I cannot find the EDSR_baseline pretrained model for ×2, ×3, and ×4. Could you please provide these files?

**Comment by Abdul--Muqeet** [comment]
https://cv.snu.ac.kr/research/EDSR/model_pytorch.tar

**Comment by Zheng222** [comment]
@Abdul--Muqeet , this tar file contains EDSR pretrained model (not EDSR_baseline).

**Comment by thstkdgus35** [comment]
Hi.

You can use a ``--pre_train download`` argument to download and load those pre-trained files.

Thank you
