### ISSUE TITLE
output image losing RGB

### ISSUE THREAD

**Issue by hulin12138** [thstkdgus35/EDSR-PyTorch#108]
I use "python3 main.py --model EDSR --data_test Demo --scale 2 --test_only --save_results" to test given image of a bird, but the result is as the follow image, i don't understand why
![0853x4_x2_sr](https://user-images.githubusercontent.com/23092730/50942133-7293a380-14c2-11e9-868e-563ea01a2baa.png)

**Comment by thstkdgus35** [comment]
Hi.

You should use a pretrained model to get a right image. Please consider the ``--pre_train download`` argument if you make it quick.

Thank you.

**Comment by yiyunchen** [comment]
I meet the same problem.
may i ask the '--pre_train download' is used for load model?
by the way,  using  '--load  ***'  can load model for testing or not ?

**Comment by weishuoycbb** [comment]
> I meet the same problem.
> may i ask the '--pre_train download' is used for load model?
> by the way, using '--load ***' can load model for testing or not ?

do you solve this?
