### ISSUE TITLE
EDSR_baseline_x4 model

### ISSUE THREAD

**Issue by thangvubk** [thstkdgus35/EDSR-PyTorch#11]
Thank you for sharing. 
I have a question: Is the provided EDSR_baseline_x4.pt trained from scratch, or it is fine-tuned from x2 model.

**Comment by thstkdgus35** [comment]
Hello.

Actually, I trained the model from scratch.

I am planning to upload all models from paper, but not sure when it will be.

Thank you.

**Comment by thangvubk** [comment]
Thank you. It would be very helpful if we have the model. Btw, did the model in pytorch reach the performance in the torch repo?

**Comment by thstkdgus35** [comment]
Sorry for the delayed comment.

PyTorch models perform better than Torch model, but there was some bug when saving result images.

There was a slight performance drop because of this issue (~0.1dB), but I fixed this problem.

I will commit the new code soon.

Thank you.
