### ISSUE TITLE
Pretrained RCAN Model link dead

### ISSUE THREAD

**Issue by aneeshvartakavi** [thstkdgus35/EDSR-PyTorch#114]
The demo.sh includes a comment to download pretrained models from this dropbox URL, which appears to be dead.

https://www.dropbox.com/s/mjbcqkd4nwhr6nu/models_ECCV2018RCAN.zip?dl=0

**Comment by thstkdgus35** [comment]
Actually, the RCAN link is not from us.

Please contact the original authors to get pre-trained models.

Otherwise, you can train RCAN from scratch with our code.

Thank you.
