### ISSUE TITLE
How to evaluate models?

### ISSUE THREAD

**Issue by gitman88** [thstkdgus35/EDSR-PyTorch#115]
How do you evaluate the models? The command I tested was this one:

`python main.py --data_test Set5 --data_range 801-900 --scale 4 --pre_train download --test_only --self_ensemble`

where my parser looks like this:

`parser.add_argument('--dir_data', type=str, default='data/datasets/',
                    help='dataset directory')`
`parser.add_argument('--dir_demo', type=str, default='../test',
                    help='demo image directory')`
`parser.add_argument('--data_train', type=str, default='DIV2K',
                    help='train dataset name')`
`parser.add_argument('--data_test', type=str, default='DIV2K',
                    help='test dataset name')`

The data folder is located at src/data/datasets/.

This the output I get:

`Making model...
Download the model

Evaluation:
0it [00:00, ?it/s]
[Set5 x4]	PSNR: nan (Best: nan @epoch 1)
Forward: 0.21s

Saving...
Total: 0.21s
`

What is the issue?

**Comment by tabetomo** [comment]
As described in README.md 
```
For these datasets, we first convert the result images to YCbCr color space and evaluate PSNR on the Y channel only. You can download benchmark datasets (250MB). Set --dir_data <where_benchmark_folder_located> to evaluate the EDSR and MDSR with the benchmarks.
```

We need to
1) download the benchmark data
https://cv.snu.ac.kr/research/EDSR/benchmark.tar
2) --dir_data [path to the benchmark folder]

It is noted the folder name for --dir_data should be "xxx" if your benchmark folder is "xxx/benchmark"
, because the software defined in data/benchmark.py adds the "benchmark" 
as
```
        self.apath = os.path.join(dir_data, 'benchmark', self.name)
```
