### ISSUE TITLE
Benchmark on custom model

### ISSUE THREAD

**Issue by gitman88** [thstkdgus35/EDSR-PyTorch#117]
How do you benchmark a pre-trained model with a custom number of residual blocks and feature maps? If I train a model with say 16 residual blocks and 16 feature maps, how would I then run it on the benchmark data (x2)? 

I tried with

`python main.py --data_test Set5+Set14+B100+Urban100+DIV2K --data_range 801-900 --scale 2 --pre_train ../experiment/edsr_x2_xs/model/model_best.pt --test_only --self_ensemble
`
The error I receive is the following:

`Traceback (most recent call last):
  File "main.py", line 23, in <module>
    model = model.Model(args, checkpoint)
  File "/home/workspace/sisr/EDSR-PyTorch/src/model/__init__.py", line 34, in __init__
    cpu=args.cpu
  File "/home/workspace/sisr/EDSR-PyTorch/src/model/__init__.py", line 103, in load
    self.model.load_state_dict(load_from, strict=False)
  File "/home/workspace/sisr/EDSR-PyTorch/src/model/edsr.py", line 78, in load_state_dict
    .format(name, own_state[name].size(), param.size()))
RuntimeError: While copying the parameter named head.0.weight, whose dimensions in the model are torch.Size([64, 3, 3, 3]) and whose dimensions in the checkpoint are torch.Size([16, 3, 3, 3]).
`

It looks like it for 2x expects 64 feature maps. Any ideas how to solve this?

**Comment by gitman88** [comment]
Solved: added --n_resblocks and --n_feats to the command.

**Comment by gitman88** [comment]
Edit: Added residual blocks and feature maps to the command and it executed. The values reported on the benchmark are however much, much lower than the evaluation during training (33 PSNR -> 17 PSNR). Something missing

**Comment by thstkdgus35** [comment]
I see.

You can comment the ``load_state_dict`` [function](https://github.com/thstkdgus35/EDSR-PyTorch/blob/72f5cc26f3033686c96209bae5e9f3e07c7e379e/src/model/edsr.py#L63-L81) I overrided and apply ``strict=True`` [here](https://github.com/thstkdgus35/EDSR-PyTorch/blob/72f5cc26f3033686c96209bae5e9f3e07c7e379e/src/model/__init__.py#L103) to see a better error message.

Please report that error message so that I can fix the issue.

**Comment by gitman88** [comment]
Ok, thanks! What do you mean report? As a new issue?

**Comment by thstkdgus35** [comment]
@gitman88 
Did you get any errors after then? If so, I would like to see the error message.
