### ISSUE TITLE
Errors when simultaneously training and testing on the DIV2K dataset?

### ISSUE THREAD

**Issue by d12306** [thstkdgus35/EDSR-PyTorch#121]
@thstkdgus35 ,thanks for your implementations first. Actually, when I train the edsr_x4 model on the DIV2K dataset, I got some errors when testing.
'''
Evaluation:
0it [00:00, ?it/s]
[DIV2K x4]      PSNR: nan (Best: nan @epoch 1)
Forward: 0.33s
'''
I try to print the idx_data when enumerating the test_loader in the ''trainer.py'' and I get 0, so I believe there any bugs when implementing the test_loader. I've seen that there are some related issues when testing on the benchmark dataset but I try the solutions out and cannot find an optimal method with respect to this issue. Could you please help me figure this out. Thanks a lot.

**Comment by thstkdgus35** [comment]
I think the directory structure is wrong.

Would you please specify your configurations so that I can take a look at it?

**Comment by d12306** [comment]
Yes, actually I make a mistake that I use a image index for validation that goes beyond the training indexes and so the loader cannot read the images out. Thanks for your attention.
