### ISSUE TITLE
Training Results are good, but testing results are really bad 

### ISSUE THREAD

**Issue by pkmonster** [thstkdgus35/EDSR-PyTorch#123]
Hi Author, 

I've made a change in EDSR model such as adding one more convolutional layer, using BN in ResBlocks.

Training results are normal with testing dataset is DIV2K, PSNR ~ 29 dB

However, when doing benchmark, all of results are really bad, PSNR ~ 11 dB.

I would like to ask you about my problem. 

1/ Is there anything wrong with model ? 
2/ How can we check that our model is correct in design or not? Using another tool to visualize etc.. ?

Thank you,

python main.py --data_test Set5+Set14+B100+Urban100+DIV2K --scale 4 --data_range 801-900 --pre_train ../experiment/resnet_x4_27feb/model/model_best.pt --test_only

![screenshot from 2019-02-28 11-07-05](https://user-images.githubusercontent.com/16741872/53538624-769a8400-3b49-11e9-8f31-7a851b7cfb8b.png)
![screenshot from 2019-02-28 11-07-12](https://user-images.githubusercontent.com/16741872/53538625-769a8400-3b49-11e9-9a45-216d67a3f58f.png)
![screenshot from 2019-02-28 11-09-39](https://user-images.githubusercontent.com/16741872/53538626-769a8400-3b49-11e9-9a65-c9942a845861.png)

**Comment by pkmonster** [comment]
![screenshot from 2019-02-28 11-07-05](https://user-images.githubusercontent.com/16741872/53538526-04c23a80-3b49-11e9-9701-4dc595328c41.png)
![screenshot from 2019-02-28 11-07-12](https://user-images.githubusercontent.com/16741872/53538528-055ad100-3b49-11e9-836f-493df63a7db2.png)

**Comment by pkmonster** [comment]
I have figured out the problem. When I set the bn = True in Residual Blocks -> Got that results. 

Is there a bug in there ?

**Comment by pkmonster** [comment]
I forgot to specify the model parameter. Problem is solved

**Comment by kk6398** [comment]
I got the same question, could you share how to deal with it?
