### ISSUE TITLE
change to binary network

### ISSUE THREAD

**Issue by suke27** [thstkdgus35/EDSR-PyTorch#133]
is it possible to convert SR normal model to binary network? according to paper, binary model will save time and memory

**Comment by thstkdgus35** [comment]
Hello.

We can convert a given SR model to binary network, and I have also tried it.

However, it is a bit different from binarizing classification networks (like AlexNet).

First, we need accurate pixel values for accurate reconstruction while correct classification does not require any accurate values (their relative magnitudes matter).

It means that we will suffer performance degradation after binarizing SR networks.

Second, it is challenging to speed up binary models in practice.

It is almost impossible with GPU, and its CPU version also requires lots of efforts for efficient implementation.

If you want a more detailed discussion, please contact me.

Thank you!
