### ISSUE TITLE
The prediction is distorted

### ISSUE THREAD

**Issue by 425183525** [thstkdgus35/EDSR-PyTorch#135]
Hello, the predicted picture is distorted (as shown in the figure).How to connect solve excuse me.thank you
![mstaSR451-pred](https://user-images.githubusercontent.com/39403315/54810050-01d9e600-4cc0-11e9-97ba-055cd924ea6e.png)
![2 2x_mstaSR3-pred](https://user-images.githubusercontent.com/39403315/54810158-50878000-4cc0-11e9-903c-9ff2de1ddad7.png)

**Comment by thstkdgus35** [comment]
Hello.

It usually happens when there is a range problem in your output image.

Try to clip output values using ``torch.clamp`` or check the range using ``torch.min()`` and ``torch.max()``.

Otherwise, you can provide the input image to me so that I can try some solutions.

Thank you!
