### ISSUE TITLE
I can't download the pretrained 'edsr_baseline_x3.pt'

### ISSUE THREAD

**Issue by zhjikoshlizhzc** [thstkdgus35/EDSR-PyTorch#136]
I use this command 'python main.py --model EDSR --scale 3 --patch_size 144 --save edsr_baseline_x3 --reset --pre_train download 'D:/Graduate/EDSR-PyTorch-master/experiment/edsr_baseline_x3/model'to download  the pretrained 'edsr_baseline_x3.pt' but error occured.

**Comment by SikkeyHuang** [comment]
the mode link is in : /src/model/edsr.py

url = {
    'r16f64x2': 'https://cv.snu.ac.kr/research/EDSR/models/edsr_baseline_x2-1bc95232.pt',
    'r16f64x3': 'https://cv.snu.ac.kr/research/EDSR/models/edsr_baseline_x3-abf2a44e.pt',
    'r16f64x4': 'https://cv.snu.ac.kr/research/EDSR/models/edsr_baseline_x4-6b446fab.pt',
    'r32f256x2': 'https://cv.snu.ac.kr/research/EDSR/models/edsr_x2-0edfb8a3.pt',
    'r32f256x3': 'https://cv.snu.ac.kr/research/EDSR/models/edsr_x3-ea3ef2c6.pt',
    'r32f256x4': 'https://cv.snu.ac.kr/research/EDSR/models/edsr_x4-4f62e9ef.pt'
}

**Comment by thstkdgus35** [comment]
Thank you, @SikkeyHuang.

You do not have to specify the download directory.

Models will be downloaded automatically at ``EDSR-PyTorch/models``.
