### ISSUE TITLE
A problem about initialization

### ISSUE THREAD

**Issue by m732367606** [thstkdgus35/EDSR-PyTorch#139]
I am very grateful for your realised code-EDSR in https://github.com/thstkdgus35/EDSR-PyTorch.
However,
I cannot find that this code employs specific initialization method while I am trying to change the initialization method to see whether I can get a better result.
I went through the whole project but cannot find which part controls the parameters initialization .😂

Could you help me solve this problem. Looking forward to your reply.😘😘
Thank you!

**Comment by ch135** [comment]
Excuse me! I have the same question. Could you tell me how to initialization?
