### ISSUE TITLE
Dataloading for seperate binary files

### ISSUE THREAD

**Issue by muneebaadil** [thstkdgus35/EDSR-PyTorch#14]
Hi, I recently migrated from Lua version to PyTorch version. However, in Lua, there was an option to load binary file for each image. I don't see that option in PyTorch. 

Since I do not have 16GB+ RAM unfortunately, I cannot have a binary file for whole dataset loaded. So, I was wondering if an option to load binary file for each image is implemented? If not, is it going to be implemented?

**Comment by thstkdgus35** [comment]
Hello. Sorry for the late comment.

I will try to implement it soon.

Thank you.

Sanghyun
