### ISSUE TITLE
Close data expansion!

### ISSUE THREAD

**Issue by zhuwanling** [thstkdgus35/EDSR-PyTorch#142]
can you tell me. how to close data expansion?
we try no_augment= True, But Useless,the total amount of training data was 9600.
We only used 800 pictures of DIV2K.

**Comment by thstkdgus35** [comment]
Hello,

Our code augments data on-the-fly, so I am not sure where the number 9600 came from.

Maybe you can check [here](https://github.com/thstkdgus35/EDSR-PyTorch/blob/54d5faa340da1be343845e6ba83b1390e613563b/src/data/srdata.py#L145) to find the answer you want.

Thank you!
