### ISSUE TITLE
NVIDIA vision

### ISSUE THREAD

**Issue by yiyunchen** [thstkdgus35/EDSR-PyTorch#144]
AssertionError:
The NVIDIA driver on your system is too old (found version 9000).
Please update your GPU driver by downloading and installing a new
version from the URL: http://www.nvidia.com/Download/index.aspx
Alternatively, go to: http://pytorch.org to install
a PyTorch version that has been compiled with your version
of the CUDA driver.

do I need update NVIDIA? and which version is need?

thank you.

**Comment by thstkdgus35** [comment]
Hello.

Just check whether your system is compatible with PyTorch, and then you can run this code without problems.

I tested this code on CUDA 10 / NVIDIA Driver 410.xx but it may not work on very old systems with small VRAM (<2GB).

Thank you!
