### ISSUE TITLE
Hi,I am a rookie. I want to know you use how much memory to test the DIV2K dataset.

### ISSUE THREAD

**Issue by echosum** [thstkdgus35/EDSR-PyTorch#150]
I use i5 +20G memory to test the DIV2K but out of memory......
Are you also using CPU to test?
The model is very lager. I want to know you use how much memory to test DIV2K data.
If I carve up the LR image to feed in model and then combination, would it have bad effect?
In your paper , how do you test the DIV2K.
Thx in advance.

**Comment by echosum** [comment]
I use i5 +20G memory to test the DIV2K but out of memory......

**Comment by thstkdgus35** [comment]
Hello.

You can use a ``--chop`` argument to do what you mentioned (carve and combine).

However, we do not recommend CPU for evaluation since it is very slow.

If you can use GPU machines, try them with the ``--chop`` argument.

Thank you.
