### ISSUE TITLE
about aclculating psnr

### ISSUE THREAD

**Issue by sxd0071** [thstkdgus35/EDSR-PyTorch#151]
Hey, sorry to bother you . I am confused about this line: valid = diff[:, :, shave:-shave, shave:-shave] ,when calculating the psnr on Y channel.
Can you share some understandings.

**Comment by thstkdgus35** [comment]
Hello.

We crop some boundary pixels to avoid boundary effects from zero-paddings.

It is also applied to RGB images as well.

Thank you.

**Comment by sxd0071** [comment]
@thstkdgus35  Thanks
