### ISSUE TITLE
The vary liabrary of the bicubic dealing will result vary result?

### ISSUE THREAD

**Issue by echosum** [thstkdgus35/EDSR-PyTorch#152]
Hi !  I used pillow Bicubic to resize HR to lR for training at start , but model always not converge.
And I try cv2 ,pillow,scipy to downsample for Bicubic,I found the LR by the ways to deal have loss with your LR .   I want to know  we have to use Matlab to bicubic downsample for LR?

**Comment by thstkdgus35** [comment]
Hello.

There is no restriction for the downsampling algorithm you use.

If you have trouble using Pillow downsampling, please check that raw image pixels are in the correct range (0\~1 for float, 0\~255 for uint8) 
before preprocessing.

Also, note that MATLAB bicubic is slightly different from others, so there can be performance degradation if there is a mismatch between train/test downsampling methods.

Thank you.
