### ISSUE TITLE
Evaluation out of memory

### ISSUE THREAD

**Issue by yiyunchen** [thstkdgus35/EDSR-PyTorch#154]
when I run the 'python main.py --model EDSR --scale 2 --save edsr_x2 --n_resblocks 32 --n_feats 256 --res_scale 0.1 --reset'.
the training is ok,
but the Evaluation out of memory?
I am confused, during the training, is the evaluation's image patch size is the same with train?  
and why the evaluation out of memoery while training are not?
thank you!

**Comment by thstkdgus35** [comment]
Hello.

Since we use patches (not full images) for training, it is hard to see out-of-memory error during the training. If you have trouble evaluating the model, please use the ``--chop`` argument.

Thank you!
