### ISSUE TITLE
Test error about run out of memory

### ISSUE THREAD

**Issue by fengshenfeilian** [thstkdgus35/EDSR-PyTorch#157]
Why it will cost two times memory when it start testing. For example in training step GPU memory is 3447 but become 6914 when testing.

**Comment by thstkdgus35** [comment]
Hello.

It happens because we use patches for training, but full images for testing.

You may avoid this issue with ``--chop`` argument.

Thank you!

**Comment by fengshenfeilian** [comment]
Thanks. I use --chop argument but got weight dimension error, and I saw that comment about some problems with --chop. So have you fix it? Thanks for your work.
