### ISSUE TITLE
About video test

### ISSUE THREAD

**Issue by 666xiaohei666** [thstkdgus35/EDSR-PyTorch#159]
Can anyone tell me   how can i run the demo on video? and what type of the video can be work mp4 or others?

**Comment by thstkdgus35** [comment]
Hello.

You can try with
``python main.py --scale 4 --pre_train download --test_only --save_results --data_test video --dir_demo [path_to_your_video_file_like_aaa/bbb/ccc.mp4]``

I am not sure about the supported formats, which totally depend on the opencv.

If you have a general mp4 file, I guess it will work correctly.

Thank you!
