### ISSUE TITLE
training error

### ISSUE THREAD

**Issue by yaolugithub** [thstkdgus35/EDSR-PyTorch#160]
Hello,I was trying to train a EDSR model with DIV2K dataset.
(1) I downloaded the DIV2K and put it in the directory  /home/yl/EDSR-PyTorch/DIV2K.  Then I changed the default of dir_data  with /home/yl/EDSR-PyTorch   in option.py. 

(2) Then I train the model with the command 
python main.py --model EDSR --scale 2 --patch_size 96 --save EDSR_baseline_x2 --ext sep_reset

(3)However, I got the error as follows
yl@hello-AI:~/EDSR-PyTorch/src$ sh demo.sh
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    import data
  File "/home/yl/EDSR-PyTorch/src/data/__init__.py", line 3, in <module>
    from dataloader import MSDataLoader
  File "/home/yl/EDSR-PyTorch/src/dataloader.py", line 17, in <module>
    from torch.utils.data.dataloader import _worker_manager_loop
ImportError: cannot import name '_worker_manager_loop'

I want to train a model with DIV2K, so can anyone help me figure out where the problem is. The README does not explain things clearly as I am confused to find out a solution.

Thanks

**Comment by thstkdgus35** [comment]
Hello.

Please refer to @ #162 If you have the problem after updating to PyTorch 1.1.0

Otherwise, please provide more details about your environment.

Thank you!

**Comment by yaolugithub** [comment]
Hello.
Thank you for your response. I have viewed your GitHub and sovled the
problem.
Thanks a lot.

Sanghyun Son <notifications@github.com> 于2019年5月10日周五 上午3:56写道：
