### ISSUE TITLE
iterations in each epoch

### ISSUE THREAD

**Issue by guiji0812** [thstkdgus35/EDSR-PyTorch#169]
hi,I am confused about the iterations in each epoch, I train with my own set with 15000 images, "test_every" is 10000 and "batch_size" is 16, "patch_size" is 384, why the iterations in one epoch is 150000,not 16x10000? I have read the code carefully but I still confused with  how   you control the iterations in every epoch

**Comment by miguelprades** [comment]
Hi,
I have similar question.
I have 1000 images but by default it takes 16000 (batch_size * test_every). 
What does the algorithm do on each epoch? 
it takes 16 images random 1000 times per epoch
Hence, does test_every control the interactions per epoch?

Thanks in advance

**Comment by guiji0812** [comment]
> Hi,
> I have similar question.
> I have 1000 images but by default it takes 16000 (batch_size * test_every).
> What does the algorithm do on each epoch?
> it takes 16 images random 1000 times per epoch
> Hence, does test_every control the interactions per epoch?
> 
> Thanks in advance
I have just understood the code, you'd better to read the file "srdata.py" ,the key is "self.repeat"  and the function "_len_(self)", , they controls the repeat times of the training images in one epoch because 
the  function "_len_(self)" decides the size of training dataset

**Comment by miguelprades** [comment]
Thanks for your answer guiji0812.
I have understood it. 
but "repeat" depend on n_patches and n_patches = args.batch_size * args.test_every. 
Just changing test_every the number of iterations per epoch is changed. 

Thanks again.
