### ISSUE TITLE
Question about getPatch method

### ISSUE THREAD

**Issue by Yuncooong** [thstkdgus35/EDSR-PyTorch#17]
Hi, may I ask how is the getPatch method in data directory's common.py gets called? I've went through the implementation and only found it's called in SRData.py's getItem function but couldn't find where the getItem function gets called. 

And another question  is if there's a way we could save the patches information we used for testing without re-trainning the model?

Thanks ahead for all the response!

**Comment by thstkdgus35** [comment]
Hello.

__getitem__ method is called by MSDataLoader class.

It is a PyTorch convention to define your own dataset, and maybe you cannot find the line that contains '__getitem__'.

Please check the link below for more details.
http://pytorch.org/docs/master/data.html#torch.utils.data.Dataset

Also, we use full images, not the patches when test time.

If you want to save the patch information you used for training, modify [this lines](https://github.com/thstkdgus35/EDSR-PyTorch/blob/e72a89368e2985b716a9762bb645cfa30266c633/code/data/SRData.py#L108-L109) and get_patch in ``data/common.py``.

Thank you!

**Comment by thstkdgus35** [comment]
Hello.

1. We extract a patch from random location of the input image. We do not fixed the number of patches from each image. Image index and patch location is all random.

2. Actually, our full-size model is designed to fit in 12GB GPU. I will upload a configuration for that problem, but I cannot guarantee how long does it take to train the model.

3. Sorry. Use --ext img to use png files. I changed it just a few days ago.

**Comment by thstkdgus35** [comment]
Sorry, there are some issues to memory-efficient forward function.

Please use smaller batch size now.

Thank you.

**Comment by Yuncooong** [comment]
Hi,

Thanks so much for the reply! We have one more question for the testing step:
Right now we want to analyse the patches of the LR image with the corresponding patches of the HR image (instead of just comparing the result of the whole image),  is there a way we can use to extract the patches from both LR images and HR images?

You've mentioned we could do it in the training step and we're wondering if it could also be achieved in test step?

Thanks so much for your help!

**Comment by thstkdgus35** [comment]
If you want to extract the patches at test stage (like our figures in the paper?), use --save_results argument to save the output images, and then make a short script to crop out the HR and LR patches.

Although we do not provide the script for extracting those patches, I think you can make it very easily.

If this answer is not what you expected, would you be more specific?

Thank you.
