### ISSUE TITLE
Where can I find EDSR_baseline_x4.pt

### ISSUE THREAD

**Issue by fredlll** [thstkdgus35/EDSR-PyTorch#173]
Hi,

Did you modify the pretrained models?  I am using a package that relying on one of your earlier pretrained models EDSR_baseline_x4.pt. But when I follow the link I only see EDSR_x4.pt. 
And there's error loading the new model :

RuntimeError: The expanded size of the tensor (64) must match the existing size (256) at non-singleton dimension 0.  Target sizes: [64, 3, 3, 3].  Tensor sizes: [256, 3, 3, 3]

Do you still have EDSR_baseline_x4.pt?
Thx

**Comment by fredlll** [comment]
Okay I realized I should use the setting of this line from demo.sh :

EDSR in the paper (x4) - from EDSR (x2)

**Comment by lisiping0817** [comment]
hello i want know how to slove this problem

**Comment by HolmesShuan** [comment]
FYI.
```python
url = {
    'r16f64x2': 'https://cv.snu.ac.kr/research/EDSR/models/edsr_baseline_x2-1bc95232.pt',
    'r16f64x3': 'https://cv.snu.ac.kr/research/EDSR/models/edsr_baseline_x3-abf2a44e.pt',
    'r16f64x4': 'https://cv.snu.ac.kr/research/EDSR/models/edsr_baseline_x4-6b446fab.pt',
    'r32f256x2': 'https://cv.snu.ac.kr/research/EDSR/models/edsr_x2-0edfb8a3.pt',
    'r32f256x3': 'https://cv.snu.ac.kr/research/EDSR/models/edsr_x3-ea3ef2c6.pt',
    'r32f256x4': 'https://cv.snu.ac.kr/research/EDSR/models/edsr_x4-4f62e9ef.pt'
}
```
