### ISSUE TITLE
Why rewrite data_loder

### ISSUE THREAD

**Issue by echosum** [thstkdgus35/EDSR-PyTorch#174]
Hi~

I am very curious why do you don't use the oringin data_loder by pytorch ,and rewrite it by yourself?

Maybe it can speed up the speed of loading data?

If it can , can you tell me how much faster it is ?

**Comment by thstkdgus35** [comment]
Hello,

We are using customized dataloader for our MDSR model.

As MDSR model is trained with varying scales of patches (for example, 48x48->96x96 and 48x48->192x192), we just add some lines to ensure that the dataloder can return a proper batch (we cannot put 48x48->96x96 and 48x48->192x192 samples in one batch).

It is not that different from the PyTorch's original code, and you can find the difference at [here](https://github.com/thstkdgus35/EDSR-PyTorch/blob/565d6feaf58616558fb01a0c65342c01a3b3a26f/src/dataloader.py#L52-L58).

I know some people may have a problem as PyTorch has changed its dataloader implementation several times.

If you are not going to train the MDSR, you can replace the dataloader to PyTorch's default version.

Thank you!

**Comment by echosum** [comment]
Yes~ Thank you for your share.
