### ISSUE TITLE
when i use model test my picture, something is wrong

### ISSUE THREAD

**Issue by keepMovin** [thstkdgus35/EDSR-PyTorch#178]
while I use final model test my picture, why the result seems is black-white, how to see the final result?

**Comment by thstkdgus35** [comment]
Hello.

It will be helpful if you can specify:

- Evaluation script
- Your input image (colors, resolutions).

Thank you!

**Comment by keepMovin** [comment]
thank you, I have solve it

**Comment by tangeroo** [comment]
@keepMovin Hi,how did you solve this problem
