### ISSUE TITLE
Hi~ I have a question about CVPRW

### ISSUE THREAD

**Issue by echosum** [thstkdgus35/EDSR-PyTorch#180]
I am very curious why is EDSR CVPRW and not CVPR. 

EDSR is state of the art method . Why isn't CVPR?

CVPRW is well below CVPR.

**Comment by thstkdgus35** [comment]
Hello.

EDSR was proposed for the [2nd NTIRE Workshop](http://www.vision.ee.ethz.ch/ntire17/) which was held in conjunction with CVPR 2017.

We note that our paper was not submitted to CVPR, but to the workshop.

Thank you for your interest!
