### ISSUE TITLE
Can improve PSNR by adding epoch？

### ISSUE THREAD

**Issue by echosum** [thstkdgus35/EDSR-PyTorch#181]
Hi~

I want to improve PSNR. I am wondering can I add training epochs to achieve?

**Comment by thstkdgus35** [comment]
Hello.

Sorry for my late response.

If you add more training epochs, it is possible to get slightly higher PSNR.

However, it will also cause an over-fitting problem and can degrade the final performance.

There are two options you can consider:

1) Use larger training patches

2) Use more data.

If you are interested in the above ideas, I can give you more explanations.

Thank you!
