### ISSUE TITLE
Question about kernel size

### ISSUE THREAD

**Issue by Auth0rM0rgan** [thstkdgus35/EDSR-PyTorch#183]
Hey @thstkdgus35,

Thanks to you and collaborators for sharing code. In the ddpbn.py, what should be the kernel_size, stride, padding for scale 3?

`def projection_conv(in_channels, out_channels, scale, up=True):
    kernel_size, stride, padding = {
        2: (6, 2, 2),
        3: (x, x, x),
        4: (8, 4, 2),
        8: (12, 8, 2)
    }`

Thanks in advance!

**Comment by thstkdgus35** [comment]
Hello.

We are not sure about the exact configuration of x3. Since x3 super-resolution is not that popular in recent works, we encourage you to use x2 or x4 if there is not any specific reason to use x3 model.

Thank you.
