### ISSUE TITLE
ValueError: num_samples should be a positive integer value, but got num_samples=0

### ISSUE THREAD

**Issue by yangpeng1995** [thstkdgus35/EDSR-PyTorch#185]
`RUNDIR: runs\seg_pascal\1980
Traceback (most recent call last):
  File "train.py", line 226, in <module>
    train(cfg, writer, logger)
  File "train.py", line 61, in train
    t_loader, batch_size=cfg["training"]["batch_size"], num_workers=cfg["training"]["n_workers"], shuffle=True
  File "C:\Users\yp\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 176, in __init__
    sampler = RandomSampler(dataset)
  File "C:\Users\yp\Anaconda3\lib\site-packages\torch\utils\data\sampler.py", line 66, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0`
How can I solve this problem?Thank you!

**Comment by Auth0rM0rgan** [comment]
Your path to training data is wrong. Try to give the correct path to data_loader.

**Comment by thstkdgus35** [comment]
Hello.

You have to specify the exact location where your training data is.

You can use the ``print`` function to see if you assigned a proper directory after [this line](https://github.com/thstkdgus35/EDSR-PyTorch/blob/565d6feaf58616558fb01a0c65342c01a3b3a26f/src/data/div2k.py#L23).

Ex)
```python
print(names_hr)
print(names_lr)
```

Thank you.

**Comment by 15793723081** [comment]
@yangpeng1995 Hello, have you solved this problem?I have encountered the same situation, I want to know what the problem is?

**Comment by riseyan** [comment]
Hello, have you solved this problem?I have encountered the same situation, I want to know what the problem is?

**Comment by yangpeng1995** [comment]
> @yangpeng1995 Hello, have you solved this problem?I have encountered the same situation, I want to know what the problem is?

The question means the number of train dataset is zero.Maybe you set wrong path, and you should check your code.

**Comment by riseyan** [comment]
> > @yangpeng1995 Hello, have you solved this problem?I have encountered the same situation, I want to know what the problem is?
> 
> The question means the number of train dataset is zero.Maybe you set wrong path, and you should check your code.

ok，thank you

**Comment by sparachi1011** [comment]
Hi, I checked the input data path and it was correct. But still i'm getting "ValueError: num_samples should be a positive integer value, but got num_samples=0".

Could some one help or provide any work around.

**Comment by malisit** [comment]
I'm not exactly sure why but if my dataset is relatively small and I set `shuffle=True` this happens. I fix this by changing `shuffle=False`. Hope this helps.

**Comment by kotchwane** [comment]
As @SonwYang said, the meaning of the error message is that the dataset has a size of 0. You can check that with `print(len(dataset))`.

In my case, it was not due to a wrong path, but to the fact that my code was creating a subset of the original dataset, larger than the original one. 
I had:
```    dataset = torch.utils.data.Subset(dataset, indices[:-50])```

while my dataset only comprised 30 elements. Setting a smaller subset solved the issue for me.

**Comment by pablomascarenhas27** [comment]
i have done everything that is mentioned above .my path is correct,my data len is 5412 which is greater than 0 but still i am getting the error
ValueError: num_samples should be a positive integer value, but got num_samples=0
can some one help me out .
i am referring the following article
https://towardsdatascience.com/text-classification-with-state-of-the-art-nlp-library-flair-b541d7add21f
can youll response as soon as possible

**Comment by pablomascarenhas27** [comment]
at first i was getting this error 
ERROR: datascience 0.10.6 has requirement folium==0.2.1, but you'll have folium 0.8.3 which is incompatible.
which i resolved using this code
!pip install --upgrade git+https://github.com/flairNLP/flair.git

then after doing that it gave me out out for the pre trained model
so i moved to the custom trained model  
import pandas as pd
data = pd.read_csv("./spam.csv", encoding='latin-1').sample(frac=1).drop_duplicates()
data = data[['v1', 'v2']].rename(columns={"v1":"label", "v2":"text"})
 
data['label'] = '__label__' + data['label'].astype(str)
data.iloc[0:int(len(data)*0.8)].to_csv('train.csv', sep='\t', index = False, header = False)
data.iloc[int(len(data)*0.8):int(len(data)*0.9)].to_csv('test.csv', sep='\t', index = False, header = False)
data.iloc[int(len(data)*0.9):].to_csv('dev.csv', sep='\t', index = False, header = False);

i ran the above code .after running the code it created train.csv,test.csv and dev.csv
so i moved to the next part of the code that starts the training process 
this is the code below
from flair.data_fetcher import NLPTaskDataFetcher
from flair.embeddings import WordEmbeddings, FlairEmbeddings, DocumentLSTMEmbeddings
from flair.models import TextClassifier
from flair.trainers import ModelTrainer
from pathlib import Path
corpus = NLPTaskDataFetcher.load_classification_corpus(Path('./'), test_file='test.csv', dev_file='dev.csv', train_file='train.csv')
word_embeddings = [WordEmbeddings('glove'), FlairEmbeddings('news-forward-fast'), FlairEmbeddings('news-backward-fast')]
document_embeddings = DocumentLSTMEmbeddings(word_embeddings, hidden_size=512, reproject_words=True, reproject_words_dimension=256)
classifier = TextClassifier(document_embeddings, label_dictionary=corpus.make_label_dictionary(), multi_label=False)
trainer = ModelTrainer(classifier, corpus)
trainer.train('./', max_epochs=10)
after i start running the above code this is wat i get
![error](https://user-images.githubusercontent.com/53001717/82661549-e06ce500-9c49-11ea-9f0b-aee08b29c11c.PNG)

**Comment by macildur** [comment]
@pablomascarenhas27  I am having a similar issue with Flair. I think the problem is that the corpus isn't getting the data from the train, test, and dev files. Unfortunately, knowing that doesn't solve the problem but at least it's a place to start from.

**Comment by yujack333** [comment]
> Hi, I checked the input data path and it was correct. But still i'm getting "ValueError: num_samples should be a positive integer value, but got num_samples=0".
> 
> Could some one help or provide any work around.

check the __len__ function. make sure it's return is the number of  dataset.

**Comment by freedom9393** [comment]
In my case file had 0 samples. Check again how you are generating your data. Maybe you are generating 0 samples?

**Comment by pablomascarenhas27** [comment]
Yes

**Comment by RRBakx** [comment]
I had the same error, in my case the 'column_name_map' was wrong. The indexes of the columns were the wrong number. The following fixed it for me:
column_name_map = {1: "text", 0: "label_sentiment"} 
Hope this helps!

**Comment by hemangjoshi37a** [comment]
cant believe this problem still exists after three years. Came here 3 years later. LOL

**Comment by bbecausereasonss** [comment]
Having this issue :/

**Comment by thewhiteflower110** [comment]
joining the club too! Deadline tomorrow, indeed a dead-line :(

**Comment by malisit** [comment]
For me this problem has only happened when I accidentally give an empty directory/list to read from to the loader. Make sure your loader actually loads the data you intend.

**Comment by thewhiteflower110** [comment]
for me, the length of Dataset was 0. Figured out there was a point in dataset script where mode was forcefully set to train.

**Comment by anandhiray** [comment]
I had this problem when my batch size was small and dataset was big. As soon as changed the batch size the problem went away.

**Comment by dipakmeher** [comment]
I had this issue. I made a mistake in the file path. As soon as I corrected it, the issue was resolved. Thanks for opening this post. Very helpful.

**Comment by Chantec** [comment]
> I had this problem when my batch size was small and dataset was big. As soon as changed the batch size the problem went away.当我的批量大小很小并且数据集很大时，我遇到了这个问题。一旦改变批量大小，问题就消失了。

so how do you deal with it?
