### ISSUE TITLE
 test EDSR_x4.pt error 

### ISSUE THREAD

**Issue by lisiping0817** [thstkdgus35/EDSR-PyTorch#187]
CUDA_VISIBLE_DEVICES=0 python3 main.py --data_test Demo --scale 4 --n_resblocks 32 --n_feats 256 --res_scale 0.1 --pre_train ../experiment/model/EDSR_x4.pt --test_only --save_results
i use this command but RuntimeError: CUDA out of memory. Tried to allocate 10.67 GiB

**Comment by thstkdgus35** [comment]
Hello.

The issue can happen if you have pretty big input images.

We recommend you to use a ``--chop`` argument which automatically slices your input images into smaller patches.

Thank you.

**Comment by xuelimin** [comment]
yes! I try this method and it work.
