### ISSUE TITLE
The computer crashed suddenly

### ISSUE THREAD

**Issue by LIMr1209** [thstkdgus35/EDSR-PyTorch#188]
def quantize(img, rgb_range):
    pixel_range = 255 / rgb_range
    return img.mul(pixel_range).clamp(0, 255).round().div(pixel_range)

In pycharm debug mode, when my code runs to this function, the computer  crash
the code runs normally Without debug ,the computer does not crash.

**Comment by thstkdgus35** [comment]
Hello.

Sorry for saying that we will not handle your issue as we are not assuming to run our code in the debug mode.

Still, you may break down a single line into multiple lines and see which part occurs the problem.

Ex)
```python
img = img.mul(pixel_range)
img = img.clamp(0, 255)
img = img.round()
...
```

Thank you.

**Comment by LIMr1209** [comment]
Thank you.
