### ISSUE TITLE
num_samples should be a positive interger

### ISSUE THREAD

**Issue by overthrowrobotics** [thstkdgus35/EDSR-PyTorch#189]
I'm trying to run the basic demo, no training. 

I've tried a bunch of different directories and pre-trained models and no matter what I try I continue to get that error. 

from demo.sh:
python3 main.py --model EDSR --scale 4 --save edsr_x4 --n_resblocks 32 --n_feats 256 --res_scale 0.1 --reset --pre_train ../experiment

When I run this I see a new directory being created in experiment called edsr_x4. I've tried copying the .pt files into the model folder in there, same result. I've also tried full path name to the folder, same error. Am I missing something obvious?

**Comment by sdlpkxd** [comment]
Same problem, need help.

**Comment by sdlpkxd** [comment]
I'm using python 3.7, it should be this that causes the error ?

**Comment by Qtodd** [comment]
> I'm using python 3.7, it should be this that causes the error ?

Hello, have you solved this problem?

**Comment by youzhaxiaomayi** [comment]
set --test_only
