### ISSUE TITLE
The question about test EDSR_x2 model

### ISSUE THREAD

**Issue by wuyujiji** [thstkdgus35/EDSR-PyTorch#19]
excuse me! I recently train the EDSR_x2 model that used your pytorch code. During trainng, the validation PSNR is normal, around 38.5dB. but after training, I used DIV2K n_val 100 to test, the reconstruction image is too poor. So I want to request for you, thank you!

**Comment by back2yes** [comment]
@wuyujiji 
Hi, did you find out the reason? I met similar problem here..
