### ISSUE TITLE
when I only use Y channel to train the MDSR meet errors

### ISSUE THREAD

**Issue by yanmenglu** [thstkdgus35/EDSR-PyTorch#191]
when I am training model with only the Y channel. I meet the error. could you help me to resolve that?
![image](https://user-images.githubusercontent.com/23131833/59689124-a6ad8600-9211-11e9-8e9e-b1a4d8f4bd34.png)

**Comment by sureJ0824** [comment]
> when I am training model with only the Y channel. I meet the error. could you help me to resolve that?
> ![image](https://user-images.githubusercontent.com/23131833/59689124-a6ad8600-9211-11e9-8e9e-b1a4d8f4bd34.png)

I have met with the same problem. Do you know how to solve it?
Thanks a lot anyway
