### ISSUE TITLE
AttributeError: 'list' object has no attribute 'shape'

### ISSUE THREAD

**Issue by carsonzhu** [thstkdgus35/EDSR-PyTorch#193]
Thanks for sharing your code, it's really a meaningful job!

When I train the model with below script:
python main.py --model EDSR --scale 4 --save edsr_x4 --n_resblocks 32 --n_feats 256 --res_scale 0.1 --reset --pre_train ../experiment/model/EDSR_x2.pt

I got below outputs:
![image](https://user-images.githubusercontent.com/13717755/59907004-9fb68b80-943c-11e9-820c-042021163ea9.png)
  File "/home/anpi-cn/workspace_min/Super-Resolution/EDSR-PyTorch/src/data/common.py", line 9, in get_patch
    ih, iw = args[0].shape[:2]
AttributeError: 'list' object has no attribute 'shape'

I know what the errors mean, but I'm just curious about if you have ever met above errors during your training process? Then how did you solve it? 
Looking forward to your reply! Thanks very much!

PS: I can run the test successfully!
![image](https://user-images.githubusercontent.com/13717755/59906872-4fd7c480-943c-11e9-8519-687dba677bef.png)

**Comment by carsonzhu** [comment]
The root cause was that the DIV2K images I used was different from the author gave. Now I could run the script normally.
![image](https://user-images.githubusercontent.com/13717755/60490486-31de4f80-9cd9-11e9-8a8e-d81b3f6dfc97.png)

**Comment by OwEnXiaoMing** [comment]
> The root cause was that the DIV2K images I used was different from the author gave. Now I could run the script normally. ![image](https://user-images.githubusercontent.com/13717755/60490486-31de4f80-9cd9-11e9-8a8e-d81b3f6dfc97.png)

请问一下这个错误具体是由什么原因引起的吗，是因为数据集跟作者的不一样吗，要重新下载一次div2k数据集吗
