### ISSUE TITLE
Incorrect Output

### ISSUE THREAD

**Issue by tanmay2298** [thstkdgus35/EDSR-PyTorch#195]
I ran the following on the DIV2K dataset.

`python main.py --model EDSR --scale 2 --save edsr_x2 --n_resblocks 32 --n_feats 256 --res_scale 0.1 --reset --ext sep_reset --batch_size 10 --epoch 300 --patch_size 96  --n_GPUs 2 --chop`

To test the model I ran

`python main.py --data_test Demo --scale 2 --pre_train 'the directory' --test_only --save_results --n_resblocks 32 --n_feats 256`

Now the output is not at all good as you can see from the images

Input : 

![0853x4](https://user-images.githubusercontent.com/24573043/60364512-5faf5580-99b4-11e9-88f5-b31ee4096220.png)

Output : 

![0853x4_x2_SR](https://user-images.githubusercontent.com/24573043/60364526-6b9b1780-99b4-11e9-816d-4516ba967cf1.png)

Where am I going wrong ? I have not changed anything from the code and wanted to test the code as is on the DIV2K.

Thanks!

**Comment by thstkdgus35** [comment]
Hello,

It seems that you ignored the ``--res_scale 0.1`` argument during your test.

Thank you.
