### ISSUE TITLE
multi-GPU

### ISSUE THREAD

**Issue by DanChen001** [thstkdgus35/EDSR-PyTorch#196]
Thank you for sharing the code.

How to trian this network with multi-GPU?   how to set the option？ Thanks

**Comment by thstkdgus35** [comment]
Hello,

You can use the ``--n_GPUs`` argument for a multi-GPU training.

Ex)
```bash
python main.py [your arguments] --n_GPUs 4
```

There can be some instabilities or minor bugs, so just let me know if you face those problems.

Thank you!

**Comment by juingzhou** [comment]
Hello, I used multiple GPUs with the following errors
`RuntimeError: Expected tensor for argument #1 'input' to have the same device as tensor for argument #2 'weight'; but device 1 does not equal 0 (while checking arguments for cudnn_convolution)
`

**Comment by Akshaypatil7** [comment]
have you solved this issue
