### ISSUE TITLE
Test but out of memory

### ISSUE THREAD

**Issue by echosum** [thstkdgus35/EDSR-PyTorch#197]
Hi~

I can't test DIV2K test dataset with 2 scale factor because I use GTX1080TI but out of memory.

If I have two 1080TI cards. Can I fix that?

**Comment by carsonzhu** [comment]
> Hi~
> 
> I can't test DIV2K test dataset with 2 scale factor because I use GTX1080TI but out of memory.
> 
> If I have two 1080TI cards. Can I fix that?



> Hi~
> 
> I can't test DIV2K test dataset with 2 scale factor because I use GTX1080TI but out of memory.
> 
> If I have two 1080TI cards. Can I fix that?

Hi, I tried to test DIV2K dataset with 2/4 scale factor using GTX 1080-8G but out of memory,
then I changed the GPU card to GTX 1080Ti-11G, now it works well.

**Comment by carsonzhu** [comment]
> Hi~
> 
> I can't test DIV2K test dataset with 2 scale factor because I use GTX1080TI but out of memory.
> 
> If I have two 1080TI cards. Can I fix that?

Hi, I tried to test DIV2K dataset with 2/4 scale factor using GTX 1080-8G but out of memory,
then I changed the GPU card to GTX 1080Ti-11G, now it works well.

**Comment by echosum** [comment]
> > Hi~
> > I can't test DIV2K test dataset with 2 scale factor because I use GTX1080TI but out of memory.
> > If I have two 1080TI cards. Can I fix that?
> 
> Hi, I tried to test DIV2K dataset with 2/4 scale factor using GTX 1080-8G but out of memory,
> then I changed the GPU card to GTX 1080Ti-11G, now it works well.


HI, I use GTX 1080TI-11G to test DIV2K dataset but out of memory. I am wondering how can you do that.

![image](https://user-images.githubusercontent.com/39319252/61141884-21ac4880-a501-11e9-9d28-0a2390b3b760.png)

I have attached my out of memory information. 
 I have calculate the GPU memory. You look, my gpu memory just have about 8G. Is my card bad?

**Comment by idealboy** [comment]
I have the same problem, but I think, we should split the DIV2K input image into different part(with a overlap shave), and run SR for each part, and then merge the final result for each part.

it seems that, the code didn't give such code for testing DIV2K.

**Comment by carsonzhu** [comment]
> > > Hi~
> > > I can't test DIV2K test dataset with 2 scale factor because I use GTX1080TI but out of memory.
> > > If I have two 1080TI cards. Can I fix that?
> > 
> > 
> > Hi, I tried to test DIV2K dataset with 2/4 scale factor using GTX 1080-8G but out of memory,
> > then I changed the GPU card to GTX 1080Ti-11G, now it works well.
> 
> HI, I use GTX 1080TI-11G to test DIV2K dataset but out of memory. I am wondering how can you do that.
> 
> ![image](https://user-images.githubusercontent.com/39319252/61141884-21ac4880-a501-11e9-9d28-0a2390b3b760.png)
> 
> I have attached my out of memory information.
> I have calculate the GPU memory. You look, my gpu memory just have about 8G. Is my card bad?

Hi, below is my testing results:
`(Pytorch-venv) anpi-cn@anpi-cn:~/workspace_min/Super-Resolution/EDSR-PyTorch/src$ python main.py --data_test Set5+Set14+B100+Urban100+DIV2K --data_range 801-900 --scale 4 --pre_train download --test_only --self_ensemble
Making model...
Download the model

Evaluation:
100%|█████████████████████████████████████████████| 5/5 [00:00<00:00,  6.38it/s]
[Set5 x4]       PSNR: 32.288 (Best: 32.288 @epoch 1)
100%|███████████████████████████████████████████| 14/14 [00:01<00:00,  6.74it/s]
[Set14 x4]      PSNR: 28.670 (Best: 28.670 @epoch 1)
100%|█████████████████████████████████████████| 100/100 [00:07<00:00, 12.60it/s]
[B100 x4]       PSNR: 27.629 (Best: 27.629 @epoch 1)
100%|█████████████████████████████████████████| 100/100 [00:38<00:00,  2.41it/s]
[Urban100 x4]   PSNR: 26.188 (Best: 26.188 @epoch 1)
100%|█████████████████████████████████████████| 100/100 [02:58<00:00,  1.51s/it]
[DIV2K x4]      PSNR: 29.043 (Best: 29.043 @epoch 1)
Forward: 227.34s

Saving...
Total: 227.34s`

**Comment by carsonzhu** [comment]
@echosum Hi, below attached is the script and testing results:

(Pytorch-venv) anpi-cn@anpi-cn:~/workspace_min/Super-Resolution/EDSR-PyTorch/src$ python main.py --data_test Set5+Set14+B100+Urban100+DIV2K --data_range 801-900 --scale 4 --pre_train download --test_only --self_ensemble
Making model...
Download the model

Evaluation:
100%|█████████████████████████████████████████████| 5/5 [00:00<00:00,  6.38it/s]
[Set5 x4]       PSNR: 32.288 (Best: 32.288 @epoch 1)
100%|███████████████████████████████████████████| 14/14 [00:01<00:00,  6.74it/s]
[Set14 x4]      PSNR: 28.670 (Best: 28.670 @epoch 1)
100%|█████████████████████████████████████████| 100/100 [00:07<00:00, 12.60it/s]
[B100 x4]       PSNR: 27.629 (Best: 27.629 @epoch 1)
100%|█████████████████████████████████████████| 100/100 [00:38<00:00,  2.41it/s]
[Urban100 x4]   PSNR: 26.188 (Best: 26.188 @epoch 1)
100%|█████████████████████████████████████████| 100/100 [02:58<00:00,  1.51s/it]
[DIV2K x4]      PSNR: 29.043 (Best: 29.043 @epoch 1)
Forward: 227.34s

Saving...
Total: 227.34s
