### ISSUE TITLE
Training with two datasets

### ISSUE THREAD

**Issue by DestinyK** [thstkdgus35/EDSR-PyTorch#199]
Hi, I want to train the model with two datasets, and these datasets have the same form as DIV2K. Like this,
`parser.add_argument('--data_train', type=str, default='DIV2K+ULTRASOUND',
                    help='train dataset name')`
`[<data.div2k.DIV2K object at 0x7f4f2e35b7b8>, <data.ultrasound.ULTRASOUND object at 0x7f4f2e35be48>]`

But I find in this code, 
```
class MyConcatDataset(ConcatDataset):
    def __init__(self, datasets):
        super(MyConcatDataset, self).__init__(datasets)
        self.train = datasets[0].train
```
self.train just init one dataset using datasets[0].
How Can I modify the code to support two datasets training. Many thanks!

**Comment by thstkdgus35** [comment]
Hello.

As you found in the code, I tried to implement the ``MyConcatDataset``, but it was more challenging than I expected.

There were several issues (about the dataset length, sampling strategy, ...). I think the easiest way is to put all the images in the same directory.

Sorry for my late response, but I hope you've already found a great solution.

Thank you!
