### ISSUE TITLE
Restart when i am training

### ISSUE THREAD

**Issue by sureJ0824** [thstkdgus35/EDSR-PyTorch#201]
hello,I am trying to run the demo.sh in my own computer
my GUP is TITAN XP
ubuntu 16.04
however, when i run the training , after epoch 1, my computer always restart
I Do not Know Why
can you help me ?
and can you tell me how much memory it cost you when you train different models?
cause i am totally fresh for code and CNNs
I really need your help
Thank you a lot

**Comment by thstkdgus35** [comment]
Hello.

I think the problem is related to your power budget. The TITAN X may require > 800W power supply to work properly, so please check it out.

Thank you

**Comment by sureJ0824** [comment]
Ouh ,you are right 
I change another budget and it works 
thanks soooo much
