### ISSUE TITLE
for batch, (lr, hr, _) in enumerate(self.loader_train):

### ISSUE THREAD

**Issue by a819411321** [thstkdgus35/EDSR-PyTorch#203]
when I train in DIV2K
Preparing loss function:
1.000 * L1
[Epoch 1]	Learning rate: 1.00e-4
Traceback (most recent call last):
  File "D:/EDSR-PyTorch/src/main.py", line 18, in <module>
    t.train()
  File "D:\EDSR-PyTorch\src\trainer.py", line 46, in train
    for batch, (lr, hr, _) in enumerate(self.loader_train):

**Comment by thstkdgus35** [comment]
Hello.

Please provide the full error message to solve the issue.

Thank you

**Comment by Leonacelli** [comment]
> Hello.
> 
> Please provide the full error message to solve the issue.
> 
> Thank you
![屏幕截图 2021-12-15 185420](https://user-images.githubusercontent.com/18423631/146173936-4ea95b20-63a0-4910-952d-ae2d99b8027e.png)
The full error message is like this
