### ISSUE TITLE
How to convert the benchmark images to low resolution image?

### ISSUE THREAD

**Issue by ninesun127** [thstkdgus35/EDSR-PyTorch#204]
`from PIL import Image`
I use the `image.resize(img,Image.BICUBIC)`function.
but it is diifferent to your low resolution image in floder。
so where can i get your code?

**Comment by thstkdgus35** [comment]
Hello.

We use MATLAB imresize('bicubic'). If you are having trouble using the MATLAB, there is a nice python implementation of the same function (Although it is a bit slow).

I think you can easily integrate it with your code. Please check [the link](https://github.com/fatheral/matlab_imresize)

Thank you
