### ISSUE TITLE
how should i do when i want to test a tif which >255?

### ISSUE THREAD

**Issue by quankainwafu** [thstkdgus35/EDSR-PyTorch#205]
Hi,i want to test a picture which pixel >255,if i use demo.sh directly,i  got a white result,how should i change the code?

Did you use unit8?how should i do if i want t use unit16?I dong't find method. 

i will appreciate for your help!

**Comment by ngcthuong** [comment]
I guess you should change the option of 'rgb_range' to 2^16.

**Comment by thstkdgus35** [comment]
Hello.

As @ngcthuong mentioned, you can do it with ``--rgb_range 65535``. You should be also careful when you are saving results images.

Thank you

**Comment by quankainwafu** [comment]
@ngcthuong  @thstkdgus35  thanks for your help。I tried to change the range ,other parameters and data types.I have got some output I want.But it seems the pixel values would change a lot when using torch ,it is very different with matlab datatypes.I would continue to learn to make the result better.
Thank you .

**Comment by wanghonen** [comment]
hello,could you please tell me how to make the result better after your learning?

**Comment by quankainwafu** [comment]
i do not know why this email find me.but well,just treat the tif as some data consist of digit which >255.from this view,update the code which control digit.in my brain,such code maybe consist in utility file,train file,test file.you would find them if you use pytorch.the work you are soupposed to do is trying to find the code's role in the project.some python code package is helpful during your work.



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | ***@***.***> |
| Date | 11/24/2022 21:11 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [sanghyun-son/EDSR-PyTorch] how should i do when i want to test a tif which >255? (#205) |

hello,could you please tell me how to make the result better after your learning?

**Comment by wanghonen** [comment]
> i do not know why this email find me.but well,just treat the tif as some data consist of digit which >255.from this view,update the code which control digit.in my brain,such code maybe consist in utility file,train file,test file.you would find them if you use pytorch.the work you are soupposed to do is trying to find the code's role in the project.some python code package is helpful during your work. | | ***@***.*** | | ***@***.*** |
> […](#)
> ---- Replied Message ---- | From | ***@***.***> | | Date | 11/24/2022 21:11 | | To | ***@***.***> | | Cc | ***@***.***>***@***.***> | | Subject | Re: [sanghyun-son/EDSR-PyTorch] how should i do when i want to test a tif which >255? (#205) | hello,could you please tell me how to make the result better after your learning? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

thank you bro
