### ISSUE TITLE
ValueError: num_samples should be a positive integer value, but got num_samples=0

### ISSUE THREAD

**Issue by 13809634102** [thstkdgus35/EDSR-PyTorch#217]
I cannot run the QuickStart(Demo) to test the algorithm with a image in the test folder.
I put the image in the test folder(EDSR-Pytorch/test), and I run the demo.sh in the src folder 
the error happen like _this:
`Traceback (most recent call last):
  File "main.py", line 33, in <module>
    main()
  File "main.py", line 22, in main
    loader = data.Data(args)
  File "/home/liangjc/Desktop/EDSR-PyTorch/src/data/__init__.py", line 31, in __init__
    num_workers=args.n_threads,
  File "/home/liangjc/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 213, in __init__
    sampler = RandomSampler(dataset)
  File "/home/liangjc/anaconda3/lib/python3.6/site-packages/torch/utils/data/sampler.py", line 94, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0
`
what's more, my pytorch is 1.2.0, my python is 3.6.5, I download the code directly with "git clone https://github.com/thstkgus35/EDSR-PyTorch.git "
thanks for your help

**Comment by 13809634102** [comment]
I have solved the problem. I have to uncomment the special line in the demo.sh, only in this way can I 
do the test

**Comment by ACer008** [comment]
> 我已经解决了这个问题。我必须取消注释demo.sh中的特殊行，只有这样才能
> 进行测试

I have encountered the same mistake with you. I have deleted all the # of demo. But still reported the mistake.Could you tell me how to solve it?

**Comment by 13809634102** [comment]
what do you want to do? If you only want to test pictures using the model, you should uncomment the special line which have comment said "#Test your own images". And the other lines should stay commented.
