### ISSUE TITLE
edsr checkerboarding issues

### ISSUE THREAD

**Issue by makslevental** [thstkdgus35/EDSR-PyTorch#219]
how did you deal with checkerboarding? all of your trained models show checkerboarding

original

![image](https://user-images.githubusercontent.com/5657668/65991019-ac467900-e45a-11e9-811e-b3696991f80b.png)

upscale 4x

![image](https://user-images.githubusercontent.com/5657668/65991036-b2d4f080-e45a-11e9-8e9b-4cbee3f095b1.png)

**Comment by makslevental** [comment]
actually the issue was that i wasn't passing in uint8 but floats. it's interesting to me though that this brought out checkerboarding

**Comment by a-sansanwal** [comment]
@makslevental can you elaborate on your fix ?

**Comment by makslevental** [comment]
@a-sansanwal rescale the pixels to [0,255]
