### ISSUE TITLE
How to super-resolve our own images?

### ISSUE THREAD

**Issue by muneebaadil** [thstkdgus35/EDSR-PyTorch#22]
Hi, apologies for a basic question; but I wasn't able to figure out how to 'test' our own images WITHOUT 'validating/evaluating' the results. I ran the following command.

```python main.py --dir_data ~/dataset --n_val 10 --offset_val 790 --scale 2 --chop_forward --model EDSR --pre_train ../experiment/model/EDSR_baseline_x4.pt --test_only --save_results```

However, it gave the following error. 

```Making model...
Loading model from ../experiment/model/EDSR_baseline_x4.pt...
	CUDA is ready!
Preparing loss function...
[{'function': L1Loss(
), 'type': 'L1', 'weight': 1.0}]

Evaluation:
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    while not t.terminate():
  File "/home/muneeb/ntire2018/code/trainer.py", line 180, in terminate
    self.test()
  File "/home/muneeb/ntire2018/code/trainer.py", line 113, in test
    self.ckp.log_test[-1, idx_scale] = eval_acc / len(self.loader_test)
ZeroDivisionError: integer division or modulo by zero
```

Could you kindly tell how to super-resolve our own set of images? Thankyou.

**Comment by thstkdgus35** [comment]
Hello.

First, place your test image in the folder ``test``

Then, please run ``demo.sh`` after uncomment 30th line. (After 'Test your own images')

You can find the results from ``experiment/test/results``

Thank you.

**Comment by kk6398** [comment]
> Hello.
> 
> First, place your test image in the folder `test`
> 
> Then, please run `demo.sh` after uncomment 30th line. (Below the 'Test your own images')
> 
> You can find the results from `experiment/test/results`
> 
> Thank you.

hello, what else we need to modify the other arguments such as 'dir_data'?
