### ISSUE TITLE
Own model

### ISSUE THREAD

**Issue by shakib-rahimi** [thstkdgus35/EDSR-PyTorch#227]
Hello, I would like to improve the model with new pictures of faces, how can I do that?
Should my dataset have a specific shape?
-------------------------------------------------- -----------------------------------------
I trained the model again with DIV2K. with this command:

python main.py - template GAN --scale 4 --save edsr_gan --reset --patch_size 96 --loss 5 * VGG54 + 0.15 * GAN --dir_data / home / rahimi / projects / dataset

How can I use the trained model now?
I have used the following command but unfortunately it does not work:
python main.py --model edsr_gan --data_test demo --scale 4 --test_only --save_results

Thank you very much
Feedback geben
Verlauf
Gespeichert
Community

**Comment by momoda-mht** [comment]
you had better add the parameter ' --pre_train', and you need to make sure that your model‘s location is right
