### ISSUE TITLE
ValueError: x and y must have same first dimension, but have shapes (0,) and (1,)

### ISSUE THREAD

**Issue by wanna-fly** [thstkdgus35/EDSR-PyTorch#228]
When I tried to train the EDSR model using default settings in this code,  an error about function plt.plot occurred.
```
Traceback (most recent call last):
  File "main.py", line 33, in <module>
    main()
  File "main.py", line 28, in main
    t.test()
  File "/home/ybx/studio/EDSR-PyTorch/src/trainer.py", line 123, in test
    self.ckp.save(self, epoch, is_best=(best[1][0, 0] + 1 == epoch))
  File "/home/ybx/studio/EDSR-PyTorch/src/utility.py", line 88, in save
    trainer.loss.plot_loss(self.dir, epoch)
  File "/home/ybx/studio/EDSR-PyTorch/src/loss/__init__.py", line 111, in plot_loss
    plt.plot(axis, self.log[:, i].numpy(), label=label)
ValueError: x and y must have same first dimension, but have shapes (0,) and (1,)
```
 I think code of line 106 in /src/loss/__init__py `axis = np.linspace(1, epoch, epoch)`should be modified into `axis = np.linspace(0, epoch+1, epoch+1)` as well as the 108th line of code in /src/utility. And it does work for me.

**Comment by yanmenglu** [comment]
you need install matplotlib

**Comment by wulongjian** [comment]
I have also meet this problem, as I follow your guidance ,I solve this problem, thanks a lot.

**Comment by Levishery** [comment]
Seems that this problem is related to pytorch version. They changed 'epoch = self.optimizer.get_last_epoch() + 1' to 'epoch = self.optimizer.get_last_epoch()' from test() in their commits on Aug 21, 2019 to support PyTorch 1.2.0. This is why this error occur.

**Comment by jucyLL** [comment]
> I have also meet this problem, as I follow your guidance ,I solve this problem, thanks a lot.


How do you solve this problem? It's just install matplotlib?

**Comment by Matthewhouch** [comment]
Fabulous! Thanks!
