### ISSUE TITLE
evaluate trained model on other datasets

### ISSUE THREAD

**Issue by zzs1994** [thstkdgus35/EDSR-PyTorch#23]
Hi, thanks for sharing the code. I have learned a lot from it. Here I have a question, how to evaluate trained model on other datasets such as BSDS100 and Manga109?

Many thanks!

**Comment by thstkdgus35** [comment]
Hello. Now my code supports BSD100 dataset.

I believe that you can easily modify those codes to implement Manga109 loader.

Thank you.
