### ISSUE TITLE
why should use pre_train?

### ISSUE THREAD

**Issue by weishuoycbb** [thstkdgus35/EDSR-PyTorch#235]
I run python3 main.py --model EDSR --scale 2  --patch_size 96 --save edsr_baseline_x2 --reset
and run python3 main.py --data_test Demo  --scale 2 --test_only --save_results
get this wrong output
![image](https://user-images.githubusercontent.com/43461329/70014454-ca913800-15b5-11ea-9b1d-401cf0fe981a.png)
I see some anwser ,say use pre_train
Why?

**Comment by thstkdgus35** [comment]
It's because you are using a randomly initialized model. Please load the pre-trained models to get a proper result. Thank you!
