### ISSUE TITLE
I want to train the custom data set.

### ISSUE THREAD

**Issue by koreadhkim** [thstkdgus35/EDSR-PyTorch#265]
https://github.com/thstkdgus35/EDSR-PyTorch/issues/51#issuecomment-409424414

Follow the above method, create custom.py, and create dataset/CUSTOM/ folders.

However, in the process of importing data, the following errors were encountered:

ValueError: some of the strides of a given numpy array are negative. This is currently not supported, but will be added in future releases.

So, after checking the print, we found that there was a part that was zeroed, such as HR size = (192, 0, 3) during dataset loading. Do you know how to solve it?

**Comment by koreadhkim** [comment]
Additionally, the HR (whole) image was converted through opencv. Here's how:

As a result,
path/CUSTOM_train_HR/ HR_images 
path/CUSTOM_train_LR_bicnic/X4/ downsampled (bicubic) HR s(LR s).

**Comment by Akshaypatil7** [comment]
Hi, I am too trying on custom data. Did you manage to successfully run training?

**Comment by koreadhkim** [comment]
Yes. I am training successfully now.

**Comment by koreadhkim** [comment]
> Hi, I am too trying on custom data. Did you manage to successfully run training?

Yes. I am training successfully now.

**Comment by Akshaypatil7** [comment]
@koreadhkim how did you solved that error

**Comment by LCA-0907** [comment]
@koreadhkim 
Also ran into this problem, how did you fix it?

**Comment by shenhaiyoulan** [comment]
@koreadhkim   same problem  could you give me some suggestions?
