### ISSUE TITLE
Can't download the pretrained model

### ISSUE THREAD

**Issue by heiheihei-ops** [thstkdgus35/EDSR-PyTorch#287]
I found that the pretrained model can't be download from https://cv.snu.ac.kr/research/EDSR/models/edsr_baseline_x4-6b446fab.pt, how can I get the model ?

**Comment by R0n12** [comment]
Same issue here, cannot access the DIV2K download link https://cv.snu.ac.kr/research/EDSR/DIV2K.tar

**Comment by thstkdgus35** [comment]
Just fixed the server issue
