### ISSUE TITLE
Weird RCAN test results 

### ISSUE THREAD

**Issue by JJangD** [thstkdgus35/EDSR-PyTorch#289]
Hello, thanks for sharing the codes.

I compared EDSRx2 and RCANx2 results.

However, the color RCANx2 result is different from the LR and EDSRx2 result.

Below are LR (original image) , EDSR and RCAN result.

![1](https://user-images.githubusercontent.com/73790655/100495111-b7468780-318b-11eb-8ab6-80d4efbd6063.PNG)

I used below command lines.

for RCAN
`python main.py --data_test Demo --scale 2 --pre_train RCAN_BIX2.pt --test_only --save_results`

for EDSR 
`python main.py --data_test Demo --scale 2 --n_resblocks 32 --n_feats 256 --res_scale 0.1 --pre_train EDSR_x2.pt --test_only --save_results`

**Comment by qcccccc** [comment]
I had the same problem, have you solved it?

**Comment by qcccccc** [comment]
I solved it by specifying the RCAN model in option...lol

**Comment by JJangD** [comment]
What do you mean 'specifying the RCAN model in option'?

**Comment by qcccccc** [comment]
“--model RCAN --n_resgroups ... --n_resblocks ... --n_feats ...“Otherwise, EDSR will be used by default

**Comment by JJangD** [comment]
Thanks!
