### ISSUE TITLE
how can I set the value of batch size and test_every?

### ISSUE THREAD

**Issue by 1187697147** [thstkdgus35/EDSR-PyTorch#294]
Hi,
I feel confused about batch size * test_every, because this setteing will increase train time per epoch.
For example, if I use DIV2K to train (total 800 HR pics and 800 LR pics), how can I set batch size and test_every so that RCAN model can use the whole trainset just one time per epoch?
Thanks for your reply!

**Comment by songyonger** [comment]
Hi,I have the same problem,did you solve it?

**Comment by 1187697147** [comment]
@songyonger,
You'd better set batch_size = 16(this value unchange).
If you want to use  more pictures from DIV2K dataset, you can set --data_test `0-900` and  change test_every.
