### ISSUE TITLE
Can I get your pytorch model on benchmark datasets

### ISSUE THREAD

**Issue by FLT19940317** [thstkdgus35/EDSR-PyTorch#32]
Hello, your work is amazing. Can I get your Pytorch model on benchmark datasets. I want to do some research based on your EDSR.

**Comment by thstkdgus35** [comment]
Hello.

Do you mean that you want to reproduce the result on benchmark datasets (Set5, Set14, Urban100, B100) from the paper?

We use same models for DIV2K and benchmark evaluations, so you can easily get the results.

Please see [these scripts](https://github.com/thstkdgus35/EDSR-PyTorch/blob/984b35d9d6832213db1f9be76bdd77976a9866ef/code/demo.sh#L32-L36)!

If I misunderstood your question, let me know.

Thank you.

**Comment by FLT19940317** [comment]
Hello, Thank for your reply. Paper's benchmark evaluations are only on the Y channel. My understanding is first transfer bechemark datasets to the Ycbcr color space, and use only Y channel as input of network resulting in output of one channel. But your trained model's input are 3 channel. So is it means that you evaluate benchmarck datasets using the RGB image as input and transfering RGB output to Ycbcr for evaluating. I don't know if I make myself clear? Thank you very much!
