### ISSUE TITLE
The count of output images is limited?

### ISSUE THREAD

**Issue by LAccordeur** [thstkdgus35/EDSR-PyTorch#37]
Hi, I am testing your Super-Resolution code. However, I find that the process would stuck when the count of output images is over 800. I am a fresh man in this area, and I don't know why this happened. Please help me.

**Comment by LAccordeur** [comment]
I change the value of param in the this file(/code/option.py), but it didn't work.

**Comment by thstkdgus35** [comment]
Hello.

I cannot understand what the count of output images exactly means. Do you have a problem when you test over 800 images?

**Comment by LAccordeur** [comment]
Yes, I meet this problem when I test over 800 images. @thstkdgus35

**Comment by thstkdgus35** [comment]
Can you show me the error message?

**Comment by LAccordeur** [comment]
I try it again with command "sh demo.sh" in the terminal directly after changing the param in option.py, and it works this time. Thank for your time. I used "subprocess" to call "sh demo.sh" in python script before and resulted in that problem.
