### ISSUE TITLE
MDSR-GAN model

### ISSUE THREAD

**Issue by ABDOELSHEMY** [thstkdgus35/EDSR-PyTorch#47]
Hi @thstkdgus35 
i download your  trained MDSR-GAN model from here https://github.com/thstkdgus35/EDSR-PyTorch/issues/27 , but i did not Succeed to use them
 i use this
 python main.py --n_threads 0 --data_test Demo --pre_train ../experiment/model/model_best.pt --test_only --scale 4 --save_results --chop --cpu

 but the result is gray photo, could you please explain the script for make it work

you say that x4 output is not that satisfying with default hyper-parameters, but when i compared your gan result with the most 2 famous srgan project on github, i found your result better than all of them, even compare to let's enhance your Gan Surprisingly do better result, so i wonder whey you did not publishing your amazing MDSR-GAN model with other models after all, thanks man for this great work and effort.

**Comment by thstkdgus35** [comment]
Hello.

You should use the exactly same model configuration that you used for training even when you are doing test only.

Please add/change to below arguments:
``--scale 2+3+4 --model MDSR``

I checked that modified script works well.

Also, we do not have a plan to publish our MDSR-GAN model til now (those works are just incremental!!), but it will be very nice if you find our work useful.

Thank you!
