### ISSUE TITLE
Training error

### ISSUE THREAD

**Issue by JadenLy** [thstkdgus35/EDSR-PyTorch#49]
Hello, I was trying to train a EDSR model with DIV2K dataset. 
I downloaded the DIV2K and put it in the directory ```~/data/DIV2K```. Then I put it as the default ```dataset_dir``` in ```option.py```. Then I train the model with the command
```
python main.py --model EDSR --scale 2 --save EDSR_x2 --n_resblocks 32 --n_feats 256 --res_scale 0.1
```
However, I got the error as follows

> Traceback (most recent call last):
  File "main.py", line 14, in <module>
    loader = data.Data(args)
  File "/home/caffe/EDSR-PyTorch/code/data/__init__.py", line 11, in __init__
    trainset = getattr(module_train, args.data_train)(args)
  File "/home/caffe/EDSR-PyTorch/code/data/div2k.py", line 7, in __init__
    args, name=name, train=train, benchmark=benchmark
  File "/home/caffe/EDSR-PyTorch/code/data/srdata.py", line 86, in __init__
    = args.test_every // (len(self.images_hr) // args.batch_size)
ZeroDivisionError: integer division or modulo by zero

I want to train a model with DIV2K, so can anyone help me figure out where the problem is. The `README` does not explain things clearly as I am confused to find out a solution. 

Thanks

**Comment by thstkdgus35** [comment]
Hello.

Please rename your ``'data`` folder to ``'dataset``.

I think this will solve your problem, but let me know if the code does not work.

Thank you.

**Comment by thstkdgus35** [comment]
Or, please modify the ``--dir_data`` argument so that your DIV2K folder lies under that directory.

Ex) ``--dir_data ../../data`` and place DIV2K under ``../../data`` folder like ``../../data/DIV2K``.

**Comment by JadenLy** [comment]
Ok, it works now thanks

**Comment by JadenLy** [comment]
One extra question here, after I start training, I found that training cannot start due to OOM error. So I wonder how much memory EDSR would take for GPU?? I have one K80 which has 11 GB available memory and yet it gives OOM error.

**Comment by kikiki1121** [comment]
Excuse me.
I changed the arguments of the folder and executed it.
However, the following error occurred.

Traceback (most recent call last):
  File "main.py", line 4, in <module>
    import data
  File "D:\EDSR-PyTorch-master\src\data\__init__.py", line 2, in <module>
    from dataloader import MSDataLoader
  File "D:\EDSR-PyTorch-master\src\dataloader.py", line 17, in <module>
    from torch.utils.data.dataloader import _worker_manager_loop
ImportError: cannot import name '_worker_manager_loop'
