### ISSUE TITLE
'code' directory interferes with InteractiveConsole

### ISSUE THREAD

**Issue by drStacky** [thstkdgus35/EDSR-PyTorch#52]
Having one of the folders named 'code' prevents InteractiveConsole from being imported, which is problematic for debugging. See [here](https://stackoverflow.com/questions/11388503/after-upgrading-eclipse-aptana-pydev-debugger-not-working).

**Comment by thstkdgus35** [comment]
Thank you for nice advice.

Since the name ``code`` has any reference, you can freely change it.

I will rename it to ``src`` or etc.
