### ISSUE TITLE
integer division or modulo by zero

### ISSUE THREAD

**Issue by freehome1** [thstkdgus35/EDSR-PyTorch#60]
I run the demo with my test images and yours, but I met a problem which is integer division or modulo by zero,in srdata.py 86, I have tried : python main.py --data_test Demo --scale 4 --pre_train ../experiment/model/EDSR_baseline_x4.pt --test_only --save_results and  python main.py --model EDSR --scale 2 --patch_size 96 --save EDSR_baseline_x2 --reset

**Comment by thstkdgus35** [comment]
Hello.

Please check the data directory whether you have the full DIV2K dataset with appropriate file structure.

Thank you.
