### ISSUE TITLE
How to get the full DIV2K dataset?

### ISSUE THREAD

**Issue by mgq1507** [thstkdgus35/EDSR-PyTorch#64]
Can you give me a baiduyun link ? Thank you very much.

**Comment by Iamanorange** [comment]
Full dataset:
https://cv.snu.ac.kr/research/EDSR/DIV2K.tar

Original download:
https://data.vision.ee.ethz.ch/cvl/DIV2K/


It is hard to upload such a big dataset to Baidu Wangpan.
