### ISSUE TITLE
Report an error when ran test

### ISSUE THREAD

**Issue by ScapeQin** [thstkdgus35/EDSR-PyTorch#68]
Making model...
Loading model from ../experiment/EDSR_x2/model/model_best.pt

Evaluation:
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "main.py", line 18, in <module>
    while not t.terminate():
  File "/mnt/lustre/ganyukang/Data_t1/shiyukai/eccv/EDSR-PyTorch-master/src/trainer.py", line 138, in terminate
    self.test()
  File "/mnt/lustre/ganyukang/Data_t1/shiyukai/eccv/EDSR-PyTorch-master/src/trainer.py", line 110, in test
    self.ckp.log[-1, idx_scale] = eval_acc / len(self.loader_test)
ZeroDivisionError: division by zero

**Comment by Iamanorange** [comment]
Check if your input data path (../../benchmark/HR and ../../benchmark/LR_bicubic) is empty, or doesn't contain any *.png file, or cann't be accessed by current user.

**Comment by ScapeQin** [comment]
@Iamanorange ok，thanks. I read the code and have solved it

**Comment by crisb-DUT** [comment]
Hi @ScapeQin @Iamanorange ,

Sorry for bothering you. What's the folder hierarchical structure of the benchmark? I cannot reproduce the PSNR results reported in the paper using pretrained model.

Thx a lot.

**Comment by ScapeQin** [comment]
@crisb-DUT  change data/__init__.py line22:  from testset = getattr(module_test, 'Benchmark')(args,  train=False) to testset = getattr(module_test, 'Benchmark')(args, name=args.data_test, train=False)
