### ISSUE TITLE
set14 test( single-channel)bridge

### ISSUE THREAD

**Issue by qingchuanhuajuan** [thstkdgus35/EDSR-PyTorch#69]
There is a picture (bridge) in set 14 that is single-channel, but the trained model requires that the input picture be three-channel. How did you solve this problem in the experiment?

**Comment by Iamanorange** [comment]
Try data.common.set_channel(image_batch, n_channels=3)

**Comment by thstkdgus35** [comment]
We stack three same gray channel for evaluation!

**Comment by 123tanchong** [comment]
I use matlab to calculate the psnr of the picture(bridge) and find that the result is much less than the result of your test code.
