### ISSUE TITLE
SRGAN method tested? 

### ISSUE THREAD

**Issue by muneebaadil** [thstkdgus35/EDSR-PyTorch#70]
Hi, 

I wanted to ask if (i) the SRGAN method is tested and (ii) is it possible to reproduce the results of the paper using this code? 

Thanks

**Comment by thstkdgus35** [comment]
You can reproduce the result with EDSR model.

Please refer to [this script](https://github.com/thstkdgus35/EDSR-PyTorch/blob/95f0571aa74ddf9dd01ff093081916d6f17d53f9/src/demo.sh#L48).

Thank you!
