### ISSUE TITLE
The effectiveness of mean value removing

### ISSUE THREAD

**Issue by DanChen001** [thstkdgus35/EDSR-PyTorch#71]
As far as I know, most deep CNN-based methods do not remove the mean value.

In this work, it seems that the mean values of RGB components are removed before training. Does the operation help improve performance? Thanks.

**Comment by thstkdgus35** [comment]
Actually, almost every CNN do normalization using dataset mean.

Although we found that removing mean value is not the essential component of our training, it will make training more stable.

Thank you.

**Comment by DanChen001** [comment]
@thstkdgus35   Thanks
