### ISSUE TITLE
The picture noise

### ISSUE THREAD

**Issue by ontheway16** [thstkdgus35/EDSR-PyTorch#73]
Hello,

Nowadays, I am carying out superresolution tests with different digital cameras with various sensor sizes (and aspect ratios), in indoor conditions. Most obvious finding is, using a bigger sensor camera in low res setting results with minimal noise and small-sensor cameras (point-shoot types) are producing ridiculous amounts of noise despite longer exposures and well lit conditions. Unfortunately, I realized that all this noise is included in superres. images, naturally. And this is killing the clarity of high-res image, stealing from the purpose of sres.

One solution may be applying image denoising prior to sres (available in openCV), this can be integrated as a command line option I believe.

But what else can be done? I am considering training noise-free Hires dataset, along with a Lores set with gaussian-noise introduced before/after bicubic downscale, do you think may it help any? Or can software tweaked to further help with this specific dataset?

Regards,

**Comment by suke27** [comment]
Hi, @ontheway16
do you try first solution, denoising prior to sres (available in openCV)
is it work in this case?

**Comment by ontheway16** [comment]
Hi @suke27 
In fact I did, and it helped very little. What's obvious is, if you can detect it (noise is visible), then sres algo can also see and enlarge it. I think pre denoising may be helpful only if noise amount is so little and become practically invisible after denoising treatment. Otherwise, noise is a big problem. I wish it could be possible to generate noise free results from small noisy images, allowing partly regeneration of output. May work with visually very similar (limited) image sets.

**Comment by ackbar03** [comment]
what kind of noises are you referring to? Do you have an example or something?
