### ISSUE TITLE
How to test the dataset of Set5(Y channel) using the trained model (RGB)

### ISSUE THREAD

**Issue by JiaqianLi** [thstkdgus35/EDSR-PyTorch#75]
hello,I want to ask you how to test the dataset of Set5(Y channel) using the trained model (RGB). In other words, the model input channel is 3 but the test dataset's channel is 1. How do you solve it?

**Comment by thstkdgus35** [comment]
Hello.

We just use RGB input/output and convert the output image to YCbCr space.

Then we use a Y channel only when evaluating traditional benchmark sets such as Set5/Set14/B100/Urban100.

Thank you!

**Comment by JiaqianLi** [comment]
Thank you for your answer！And I have another question, are the codes that convert the images to the YCbCr space and calculate the PSNR of the Y channel images provided，or  these should be written by myself ?

**Comment by thstkdgus35** [comment]
For the above datasets I mentioned, my code calculate PSNR of the Y channel automatically.

Please use an argument such as ``--data_test Set5``.

If you have any troubles, set ``benchmark=True`` when calling [calc_psnr](https://github.com/thstkdgus35/EDSR-PyTorch/blob/95f0571aa74ddf9dd01ff093081916d6f17d53f9/src/utility.py#L133) to evaluate the PSNR of Y channel

**Comment by JiaqianLi** [comment]
Ok, I understand it. Thanks a lot!
