### ISSUE TITLE
What is the required OpenCV version?

### ISSUE THREAD

**Issue by KNLc** [thstkdgus35/EDSR-PyTorch#76]
I try to run the code by demo.sh and I encountered a problem that "No module named 'cv2' ". I noticed that videotester.py import cv2, but cv2 not mentioned in the dependencies.
Should I install OpenCV or OpenCV3 now?  What is the required OpenCV version ? I guess it is OK to use OPENCV3. Right?

**Comment by thstkdgus35** [comment]
Hello.

The required cv2 version is 3.xx, but you do not have to install it unless you want to use video input/output.

Please remove [this line](https://github.com/thstkdgus35/EDSR-PyTorch/blob/70294bb6170651dd1c2435da18a34c0e2cf63511/src/main.py#L9) to avoid the error message.

I will update the README soon.

Thank you!
