### ISSUE TITLE
How do I control the number of iterations in each epoch, as if he would change with test_every?

### ISSUE THREAD

**Issue by Errorkiller** [thstkdgus35/EDSR-PyTorch#78]
hi,
How do I control the number of iterations in each epoch, as if it would change with 'test_every'?

**Comment by thstkdgus35** [comment]
Hello.

In each epoch, you will have ``batch_size * test_every`` many samples.

Therefore, if you would like to use 800 samples with ``batch_size=4``, set ``test_every=200``.

Thank you.

**Comment by guiji0812** [comment]
hi, the number of my training images is 15000, I set the batches 16 and test_every 10000,then the number of samples in each epoch is 150000, not the 16x10000, why?

**Comment by guiji0812** [comment]
> hi,
> How do I control the number of iterations in each epoch, as if it would change with 'test_every'?

hello, I am also confused with this problem,the number of my training images is 15000, I set the batches 16 and test_every 10000,then the number of samples in each epoch is 150000, not the 16x10000, why?Could you give me some explanations?thank you
