### ISSUE TITLE
div2k range question when --ext bin

### ISSUE THREAD

**Issue by splinter22** [thstkdgus35/EDSR-PyTorch#84]
when training, valid range is 801-810, when I use --ext bin, it generates a bin.
when testing, valid range is 801-900,  and when I use --ext bin, it uses the existed 10-images bin instead of generates a 100-images bin.

**Comment by thstkdgus35** [comment]
Hello.

You can evaluate the model on 801-900 by setting the input arguments.

Please try with ``--data_range 1-800/801-900`` and let me know if it works.

With ``--test_only``, I think ``--data_range 801-900`` will also work.

Thank you!
