### ISSUE TITLE
Please help me with this error - ValueError: math domain error

### ISSUE THREAD

**Issue by songkeeh** [thstkdgus35/EDSR-PyTorch#89]
hi,

i keep getting the below error on random epoch.
pytorch0.4.0, python 3.6.6 are installed.
tensor printout is just my log to see if mse in math.log(mse) is really zero or not which turned out to be real zero.
I have followed your instructions described on the web of this site and nothing more added before training.

tensor([[[[ 0.,  0.,  0.,  ...,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  ...,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  ...,  0.,  0.,  0.],
          ...,
          [ 0.,  0.,  0.,  ...,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  ...,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  ...,  0.,  0.,  0.]],

         [[ 0.,  0.,  0.,  ...,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  ...,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  ...,  0.,  0.,  0.],
          ...,
          [ 0.,  0.,  0.,  ...,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  ...,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  ...,  0.,  0.,  0.]],

         [[ 0.,  0.,  0.,  ...,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  ...,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  ...,  0.,  0.,  0.],
          ...,
          [ 0.,  0.,  0.,  ...,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  ...,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  ...,  0.,  0.,  0.]]]], device='cuda:0')
tensor(0., device='cuda:0')
Traceback (most recent call last):
  File "main.py", line 26, in <module>
    t.test()
  File "/home/ubuntu/edsr_pytorch/src/trainer.py", line 95, in test
    sr, hr, scale, self.args.rgb_range, dataset=d
  File "/home/ubuntu/edsr_pytorch/src/utility.py", line 184, in calc_psnr
    return -10 * math.log10(mse)
ValueError: math domain error

**Comment by thstkdgus35** [comment]
Hello.
Would you describe me 1) which script you executed 2) your os / cuda version ?
