### ISSUE TITLE
low psnr performance when using the pre-trained model 'EDSR_baseline_x4.pt'

### ISSUE THREAD

**Issue by XL2013** [thstkdgus35/EDSR-PyTorch#9]
Hi,
I used the pre-trained model and test it on Set4 and BSD100, but the performance is not good.
The psnr result:
Set5 : 26.86; BSD100:25.15.

The test code: save result images
```python
for iteration, batch in enumerate(data_loader,1):
    img = batch[0]
    img = Variable(img, volatile=True)
    if cuda:
        img = img.cuda()
    out = my_model(img)
    out_img = out.cpu().data[0].numpy()
    out_img *= 255.0
    out_img = out_img.clip(0,255)
    out_img = out_img.transpose(1,2,0)
    out_img = Image.fromarray(np.uint8(out_img))
    
    save_path = save_dir+'/'+set_name+'_'+str(iteration)+'.png'
    out_img.save(save_path)
    print('output image saved to', save_path)
```
and the evaluate code:
```matlab
function psnr=compute_psnr(im1,im2)
if size(im1, 3) > 1
    im1 = rgb2ycbcr(im1);
    im1 = im1(:, :, 1);
end

if size(im2, 3) == 3
    im2 = rgb2ycbcr(im2);
    im2 = im2(:, :, 1);
end

cropPix     = 4;
im1 = shave(im1, [cropPix, cropPix]);
im2  = shave(im2, [cropPix, cropPix]); 

imdff = double(im1) - double(im2);
imdff = imdff(:);

rmse = sqrt(mean(imdff.^2));
psnr = 20*log10(255/rmse);
end

function I = shave(I, border)
I = I(1+border(1):end-border(1), ...
      1+border(2):end-border(2), :, :);
end
```
Besides, the test LR iand HR images were provided by [SelfExSR](https://github.com/jbhuang0604/SelfExSR)

Any advice?

**Comment by thstkdgus35** [comment]
Hello.

I evaluated our model with your script and got 32.11dB PSNR on Set5.

I think there is an error in your save code.

To get the output images without any additional script, you can put your test images in ```test/``` and run ```demo.sh```  script in ```code/```.

You can find the results from ```experiment/test/results```.

Thank you.

Sanghyun.

**Comment by XL2013** [comment]
Hi, Sanghyun

Thank you for your reply!

I run the demo.sh  and got the same result, 32.11.

The reason for my problem is the **Tensor transform operation**.

I used **torchvision.transforms.ToTensor()**, so the range of my LR input images was [0,1], which was [0. 255] in your implementation.

best.
