### ISSUE TITLE
Images?

### ISSUE THREAD

**Issue by shreyaskamathkm** [thstkdgus35/EDSR-PyTorch#93]
Hi,

Can you provide a link that contains the Super-Resolved images (of different scales) from the benchmark datasets? Like a zip file or something similar?

**Comment by thstkdgus35** [comment]
Hello.

Please download those images from[here](https://cv.snu.ac.kr/research/EDSR/result_image/edsr-results.tar).

If you need more results, please let me know!

Thank you.

**Comment by shreyaskamathkm** [comment]
Thank you so much! I will run your code for the rest of the images.
