### ISSUE TITLE
psnr is nan 

### ISSUE THREAD

**Issue by Ji-qing** [thstkdgus35/EDSR-PyTorch#95]
Hi, 
I have also encountered a  problem in #79 . After I changed the dir_data to the folder location of my dataset , the problem was not solved.
```
parser.add_argument('--dir_data', type=str, default='../../data123',
                    help='dataset directory')
```
And I modified the --dir_data argument so that your DIV2K folder lies under that directory.

that) --dir_data ../../data123 and place DIV2K under ../../data123 folder like ../../data123/DIV2K.

But the problem was not solved. I used python3.5, pytorch0.4.0; and used command: `main.py --model EDSR --save edsr_x2 --n_resblocks 32 --n_feats 256 --res_scale 0.1 --reset`
I posted some of the results below.
```
$ python3 main.py --model EDSR --save edsr_x2 --n_resblocks 32 --n_feats 256 --res_scale 0.1 --reset
DIV2K
Making model...
Preparing loss function:
1.000 * L1
[Epoch 1]	Learning rate: 1.00e-4

Evaluation:
0it [00:00, ?it/s]
aa
[DIV2K x2]	PSNR: nan (Best: nan @epoch 1)
Forward: 0.13s

Saving...
Total: 0.48s

[Epoch 2]	Learning rate: 1.00e-4

Evaluation:
0it [00:00, ?it/s]
aa
[DIV2K x2]	PSNR: nan (Best: nan @epoch 1)
Forward: 0.13s

Saving...
Total: 0.57s

[Epoch 3]	Learning rate: 1.00e-4

Evaluation:
0it [00:00, ?it/s]
aa
[DIV2K x2]	PSNR: nan (Best: nan @epoch 1)
Forward: 0.13s

Saving...
Total: 1.22s

[Epoch 4]	Learning rate: 1.00e-4

Evaluation:
0it [00:00, ?it/s]
aa
[DIV2K x2]	PSNR: nan (Best: nan @epoch 1)
Forward: 0.13s

Saving...
Total: 1.19s
```
looking for your help.
Thank you.

**Comment by Alxemade** [comment]
A few days ago I encountered the same problem as you, and then I modified the dir_data parameter. You can go to the upper DIV2K directory like data123  or dataset, and use the `pwd` command in the Linux environment to find you dir. I hope this will help you. 
![image](https://github.com/Alxemade/Screenshots/raw/master/20181207/Selection_015.png)
![image](https://github.com/Alxemade/Screenshots/raw/master/20181207/Selection_016.png)
