### ISSUE TITLE
how to make the jpeg LR training dataset?

### ISSUE THREAD

**Issue by splinter22** [thstkdgus35/EDSR-PyTorch#97]
Should the jpeg parameter of each image be the same(for example ,75)？Or just add random jpeg noise?
And when testing, can the network adapt different jpeg parameter? (for example, 60~90,maybe lower, we don't know the jpeg parameter when testing real image)

**Comment by thstkdgus35** [comment]
I did not test the random configuration, so it is worth trying.

What I tried is fixing some possible quality factors during training.

If you use only one quality factor (ex. 75), your model will fail with other quality factors (ex. 100).

However, I found that mixing different quality factors during training can solve this issue efficiently.

For example, you can mix 75 and 100 (+clean png file if you want) for your training.

Then, the model will work well on 75, 100, and even arbitrary quality factors between 75 and 100 (ex. 80).

Please feel free to ask additional questions if you want!

Thank you.
